name: test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node Active LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Deps
        run: npm ci
      - name: Build & Test
        run: |
          npm run build
          npm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
